# Change these first
owner: donfn # Your GitHub organization or username, where this repository lives
repo: unistudents-status # The name of this repository

sites:
  - name: Υπηρεσία Νέων & Ανακοινώσεων (UniNews)
    url: https://gohan.unistudents.gr
  - name: Οικονομικό Πανεπιστήμιο Αθηνών
    url: https://e-grammateia.aueb.gr/unistudent/
  - name: Αριστοτέλειο Πανεπιστήμιο
    url: https://universis-api.it.auth.gr/api
  - name: Δημοκρίτειο Πανεπιστήμιο Θράκης
    url: https://oauth.duth.gr/login
  - name: Ελληνικό Μεσογειακό Πανεπιστήμιο
    url: https://universis-api.hmu.gr/api/
  - name: Χαροκόπειο Πανεπιστήμιο Αθηνών
    url: https://e-studies.hua.gr/unistudent/
    __dangerous__insecure: true
  - name: Εθνικό Μετσόβιο Πολυτεχνείο
    url: https://backend.central.ntua.gr/
  - name: Εθνικό Μετσόβιο Πολυτεχνείο (ΣΥΜΜΗ)
    url: https://students.ece.ntua.gr/login
  - name: Πάντειο Πανεπιστήμιο
    url: https://foit.panteion.gr/declare/Login.aspx
    __dangerous__insecure: true
  - name: Πανεπιστήμιο Αιγαίου
    url: https://uni-extapi.aegean.gr/api/
  - name: Πανεπιστήμιο Αιγαίου (Σ.Ε.Φ.)
    url: https://sef.samos.aegean.gr/index.php
  - name: Πολυτεχνείο Κρήτης
    url: https://universis-api.tuc.gr/api
  - name: Εθνικό Καποδιστριακό Πανεπιστήμιο
    url: https://my-studies.uoa.gr/Secr3w/connect.aspx
  - name: Πανεπιστήμιο Πατρών
    url: https://progress.upatras.gr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.unistudents.gr
  # baseUrl: /your-repo-name
  logoUrl: https://unistudents.gr/blog/content/images/2022/01/logo2-1024x341-1-1.png
  name: Κατάσταση Συστημάτων
  introMessage: "Σε αυτή τη σελίδα μπορείς να παρακολουθείς την κατάσταση των συστημάτων που στηρίζεται το UniStudents, όπως: Cloud services, Βάσεις Δεδομένων, Φοιτητολόγια κλπ."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
