# Change these first
owner: donfn # Your GitHub organization or username, where this repository lives
repo: unistudents-status # The name of this repository

sites:
  - name: Υπηρεσία Νέων & Ανακοινώσεων (UniNews)
    url: gohan.unistudents.gr/metrics/uptime
  - name: Α.Σ.ΠΑΙ.Τ.Ε
    url: https://studentweb.aspete.gr/
  - name: Αριστοτέλειο Πανεπιστήμιο
    url: https://universis-api.it.auth.gr/api
  - name: Γεωπονικό Πανεπιστήμιο Αθηνών
    url: https://unistudent.aua.gr/
  - name: Δημοκρίτειο Πανεπιστήμιο Θράκης
    url: https://oauth.duth.gr/login
  - name: Διεθνές Πανεπιστήμιο Ελλάδος (TEITHE)
    url: http://pithia.teithe.gr/unistudent/
  - name: Διεθνές Πανεπιστήμιο Ελλάδος (CM) (TCP Ping)
    check: "tcp-ping"
    url: 83.212.60.104
    port: 443
  - name: Διεθνές Πανεπιστήμιο Ελλάδος (TEIEMT)
    url: https://e-secretariat.teiemt.gr/unistudent/
  - name: Εθνικό Μετσόβιο Πολυτεχνείο
    url: https://backend.central.ntua.gr/
  - name: Εθνικό Μετσόβιο Πολυτεχνείο (ΣΥΜΜΗ)
    url: https://students.ece.ntua.gr/login
  - name: Εθνικό Καποδιστριακό Πανεπιστήμιο
    url: https://my-studies.uoa.gr/Secr3w/connect.aspx
  - name: Ελληνικό Μεσογειακό Πανεπιστήμιο
    url: https://universis-api.hmu.gr/api/
  - name: Ιόνιο Πανεπιστήμιο
    url: https://dias.ionio.gr/
  - name: Οικονομικό Πανεπιστήμιο Αθηνών
    url: https://e-grammateia.aueb.gr/unistudent/
  - name: Πανεπιστήμιο Αιγαίου (UNIVERSIS)
    url: https://uni-extapi.aegean.gr/api/
  - name: Πανεπιστήμιο Αιγαίου (Σ.Ε.Φ.)
    url: https://sef.samos.aegean.gr/index.php
  - name: Πανεπιστήμιο Αιγαίου (ICARUS)
    url: https://icarus-icsd.aegean.gr/
  - name: Πανεπιστήμιο Δυτικής Αττικής
    url: https://services.uniwa.gr/
  - name: Πανεπιστήμιο Δυτικής Μακεδονίας
    url: https://students.uowm.gr/
  - name: Πανεπιστήμιο Ιωαννίνων
    url: https://classweb.uoi.gr/
  - name: Πανεπιστήμιο Κρήτης
    url: https://student.cc.uoc.gr/
  - name: Πανεπιστήμιο Πατρών
    url: https://progress.upatras.gr
  - name: Πανεπιστήμιο Πειραιώς
    url: https://students.unipi.gr/
  - name: Πανεπιστήμιο Πελοποννήσου (Cardisoft)
    url: https://e-secretary.uop.gr/UniStudent/
  - name: Πανεπιστήμιο Πελοποννήσου (TEIPEL)
    url: http://www.webgram.teipel.gr/unistudent/login.asp
  - name: Πάντειο Πανεπιστήμιο
    url: https://foit.panteion.gr/declare/Login.aspx
    __dangerous__insecure: true
  - name: Πολυτεχνείο Κρήτης
    url: https://universis-api.tuc.gr/api
  - name: Πρώην ΤΕΙ Δυτικής Ελλάδας (TCP Ping)
    check: "tcp-ping"
    url: 195.251.8.50
    port: 443
  - name: Χαροκόπειο Πανεπιστήμιο Αθηνών
    url: https://e-studies.hua.gr/unistudent/
    __dangerous__insecure: true
    
status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.unistudents.gr
  # baseUrl: /your-repo-name
  logoUrl: https://unistudents.gr/blog/content/images/2022/01/logo2-1024x341-1-1.png
  name: Κατάσταση Συστημάτων
  introMessage: "Σε αυτή τη σελίδα μπορείς να παρακολουθείς την κατάσταση των συστημάτων που στηρίζεται το UniStudents, όπως: Cloud services, Βάσεις Δεδομένων, Φοιτητολόγια κλπ."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
